# Generated by Django 4.1.5 on 2023-03-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[("Bihar", "Bihar"), ("MP", "MP")], max_length=50
                    ),
                ),
                ("location", models.CharField(max_length=50)),
                ("pimage", models.ImageField(blank=True, upload_to="pimage")),
                ("rdoc", models.FileField(blank=True, upload_to="rdoc")),
            ],
        ),
    ]
